# Generated by Django 3.2.13 on 2022-05-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcart',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
