# Generated by Django 3.2.13 on 2022-05-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_foodcart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
